src/Entity/Profesion.php
<?php

namespace App\Entity;

use App\Repository\ProfesionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfesionRepository::class)
 */
class Profesion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nombre;

    //RELACIIONES
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="profesion")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }
}

src/Controller/DashBoardController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Comentarios;
use App\Entity\Post;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashBoardController extends AbstractController
{
    /**
     * @Route("/", name="dash_board")
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        //COMPROBAR QUE HAYA UN USUARIO CONECTADO
        $user = $this->getUser();
        if ($user){
            //TRAER LOS POST DE LA BASE DE DATOS
            $em = $this->getDoctrine()->getManager();
            $query = $em->getRepository(Post::class)->BuscarTodosPost();
            //$post = $em->getRepository(Post::class)->findAll();
            //TRAER LOS COMENTARIOS DEL USUARIO
            $comentarios = $em->getRepository(Comentarios::class)->ComentariosUsuario($user->getId());
            //PAGINADOR
            $pagination = $paginator->paginate(
                $query, /* query NOT result */
                $request->query->getInt('page', 1), /*page number*/
                2 /*limit per page*/
            );

            return $this->render('dash_board/index.html.twig', [
                'pagination' => $pagination,
                'comentarios' => $comentarios
            ]);
        }else{
            return $this->redirectToRoute('app_login');
        }

    }
}

templates/dash_board/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent()}}-Dashboard {% endblock %}

{% block body %}
    {{ parent() }}

    <div class="container">
        <div class="row">
            <div class="col-md-8 cursor">
                {% for post in pagination %}
                    <div class="bg-white rounded p-3 my-3" onclick="window.location.href='{{ path('VerPost',{id:post.id}) }}'">
                        <div class="d-flex bd-hightlight">
                            <div class="p-2 flex-grow-1 bd-highlight">
                                <h3>{{ post.titulo }}</h3>
                                <div class="my-3 bg-yellow"><i class="fa fa-user"></i><strong>Creado por: {{ post.nombre }}</strong></div>
                                <div class="bg-green"><i class="fa fa-clock"></i><strong>Fecha de publicación: {{ post.fecha_publicacion | date('Y-m-d') }}</strong></div>
                            </div>
                            <div class="p-2 bd-highlight">
                                <div class="align-self-center">
                                    <img class="rounded" src="{{ asset('/uploads/imagenes/'~post.foto) }}" width="150px">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-4">
                <div class="bg-white rounded p-3 my-3">
                    <h4>Comentarios</h4>
                        {% for coment in comentarios %}
                            <div class="bg-white rounded p-3 my-3"  onclick="window.location.href='{{ path('VerPost',{id:coment.id}) }}'">
                                <div class="d-flex bd-hightlight">
                                    <div class="p-2 flex-grow-1 bd-highlight">
                                        {{ coment.titulo }}
                                    </div>
                                    <div class="p-2 bd-highlight">
                                        {{ coment.fecha_publicacion | date('Y-m-d') }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>
        </div>

    </div>

{% endblock %}